# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookAuthors_app', '0002_books_authors_books_authorsmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorManager',
        ),
        migrations.DeleteModel(
            name='BookManager',
        ),
        migrations.DeleteModel(
            name='Books_AuthorsManager',
        ),
    ]
